# based on 4.4BSD src/sys/kern/makesyscalls.sh

# All of the documentation and software included in the 4.4BSD and 4.4BSD-Lite
# Releases is copyrighted by The Regents of the University of California.
#
# Copyright 1979, 1980, 1983, 1986, 1988, 1989, 1991, 1992, 1993, 1994
# 	The Regents of the University of California.  All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. All advertising materials mentioning features or use of this software
#    must display the following acknowledgement:
# This product includes software developed by the University of
# California, Berkeley and its contributors.
# 4. Neither the name of the University nor the names of its contributors
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.

#! /bin/sh -
#	@(#)makesyscalls.sh	8.1 (Berkeley) 6/10/93

set -e

# output files:
sysnames="sysnames.c"
syshdr="syscall.h"
syssw="syscall.c"
sysasm="usys.S"
sysdhdr="usys.h"

# tmp files:
sysdcl="sysent.dcl"
sysent="sysent.switch"

trap "rm $sysdcl $sysent" 0

case $# in
    0)	echo "Usage: $0 input-file" 1>&2
	exit 1
	;;
esac

awk -F'\t' < $1 "
	BEGIN {
		sysdcl = \"$sysdcl\"
		sysent = \"$sysent\"
		sysnames = \"$sysnames\"
		syshdr = \"$syshdr\"
		sysasm = \"$sysasm\"
		sysdhdr = \"$sysdhdr\"
		infile = \"$1\"
		"'

		printf "/*\n * System call switch table.\n *\n" > sysdcl
		printf " * DO NOT EDIT-- this file is automatically generated.\n" > sysdcl


		printf "/*\n * System call names.\n *\n" > sysnames
		printf " * DO NOT EDIT-- this file is automatically generated.\n" > sysnames

		printf "/*\n * System call numbers.\n *\n" > syshdr
		printf " * DO NOT EDIT-- this file is automatically generated.\n" > syshdr
		 
		printf "/*\n * System calls asm stubs.\n *\n" > sysasm
		printf " * DO NOT EDIT-- this file is automatically generated.\n" > sysasm

		printf "/*\n * System calls.\n *\n" > sysdhdr
		printf " * DO NOT EDIT-- this file is automatically generated.\n" > sysdhdr
	}
	NR == 1 {
		printf " * created from%s\n */\n\n", $0 > sysdcl
		printf("#include \"%s\"\n", syshdr) > sysdcl
		printf "int sys_nosys();\n\n" > sysdcl

		printf "int (*syscalls[])() = {\n" > sysent

		printf " * created from%s\n */\n\n", $0 > sysnames
		printf "char *syscallnames[] = {\n" > sysnames

		printf " * created from%s\n */\n\n", $0 > syshdr

		printf " * created from%s\n */\n\n", $0 > sysasm
		printf("#include \"%s\"\n", syshdr) > sysasm
		printf ".local sysent\n\n" > sysasm
		
		printf " * created from%s\n */\n\n", $0 > sysdhdr

		next
	}
	NF == 0 || $1 ~ /^;/ {
		next
	}
	$1 ~ /^#[ 	]*if/ {
		print > sysent
		print > sysdcl
		print > sysnames
		savesyscall = syscall
		next
	}
	$1 ~ /^#[ 	]*else/ {
		print > sysent
		print > sysdcl
		print > sysnames
		syscall = savesyscall
		next
	}
	$1 ~ /^#/ {
		print > sysent
		print > sysdcl
		print > sysnames
		next
	}
	syscall != $1 {
		printf "%s: line %d: syscall number out of sync at %d\n", \
		   infile, NR, syscall
		printf "line is:\n"
		print
		exit 1
	}
	{	args = $5
		for (i = 6; i <= NF; i++)
			args = args " " $i
	}
	$2 == "STD" {
		printf("int sys_%s();\n", $3) > sysdcl

		printf("\t[SYS_%s] =\tsys_%s,\t\t\t/* %d = %s */\n", \
		    $3, $3, syscall, $3) > sysent

		printf("\t\"%s\",\t\t\t/* %d = %s */\n", \
		    $3, syscall, $3) > sysnames

		printf("#define\tSYS_%s\t%d\n", \
		    $3, syscall) > syshdr
		
		printf(".globl %s\n", $3) > sysasm
		printf("%s:\nmov $SYS_%s, %rax\n", $3, $3) > sysasm
		print("call sysent\nret\n") > sysasm

		printf("%s %s%s;\n", $4, $3, $5) > sysdhdr

		syscall++

		next
	}
	$2 == "UNIMPL" {
		#printf("\t[%d] nosys },\t\t\t/* %d = %s */\n", \
		#    syscall, comment) > sysent
		printf("\t[SYS_%s] =\tsys_nosys,\t\t\t/* %d = %s */\n", \
		    $3, $3, syscall, $3) > sysent

		printf("\t\"#%d\",\t\t\t/* %d = %s */\n", \
		    syscall, syscall, $3) > sysnames
		printf("#define\tSYS_%s\t%d\n", \
		    $3, syscall) > syshdr
		syscall++
		next
	}
	{
		printf "%s: line %d: unrecognized keyword %s\n", infile, NR, $2
		exit 1
	}
	END {
		print("\n") > sysdcl

		printf("};\n\n") > sysent
		printf("int nsyscall = sizeof(syscalls) / sizeof(syscalls[0]);\n") > sysent

		printf("};\n") > sysnames

		print("sysent:") > sysasm
		printf("mov %rcx, %r10\nsyscall\nret\n") > sysasm
	} '

cat $sysdcl $sysent >$syssw
